### ISSUE TITLE
[Question] Is the labeled dataset contained in the unlabeled dataset as well?

### ISSUE THREAD

**Issue by f-lng** [google-research-datasets/paws#1]
Hello,

Thank you very much for sharing this dataset, great work.

I have one question: Are the datapoints from  "PAWS-Wiki Labeled (Final)" contained in "PAWS-Wiki Unlabeled (Final)" as well?

Thanks!

**Comment by yuanzh** [comment]
Thanks for your interest! The datapoints from "Labeled" are not contained in "Unlabeled"

**Comment by f-lng** [comment]
I found an overlap of 507 pairs, which is minimal, but I figured you would like to know anyway :-)

**Comment by yuanzh** [comment]
Nice catch! Thanks for letting us know the issue!
